### PR TITLE
fixed the tree-sitter grammar to allow any primary term on rhs of IN

### PR DESCRIPTION
**Pull request by ginsbach**
This addresses https://github.com/tree-sitter/tree-sitter-ql/pull/8.

### CODE REVIEW

**Comment by tclem** [comment]
@maxbrunsfeld had a good suggestion to [bump the commit sha](https://github.com/tree-sitter/tree-sitter-ql/blob/master/script/fetch-examples#L17) for github/codeql which is used in the CI run (just to something newer like HEAD of default branch).

**Comment by ginsbach** [comment]
redo failed

**Comment by maxbrunsfeld** [comment]
```
Downloading and installing node v10.22.1...
Downloading https://nodejs.org/dist/v10.22.1/node-v10.22.1-linux-x64.tar.xz...
```

Looks like some of the nodejs.org servers are down?

**Comment by ginsbach** [comment]
redo failed

**Comment by maxbrunsfeld** [comment]
```
fatal: Could not parse object 'f48827fd1b67a0ab468d548781c882abfedf0b05'.
The command "script/fetch-examples" exited with 128.
```

It looks like that sha isn't present in the main github/codeql repo. Should we use the latest commit on `main`, github/codeql@86404af50100b409b18e62651295e79393a6016a ?

**Pull request merged**
